# Generated by Django 4.0.5 on 2023-02-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('query_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('document_id', models.CharField(blank=True, max_length=36, null=True)),
                ('responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('permit', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_email', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('superviser_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('level_3', models.CharField(blank=True, max_length=255, null=True)),
                ('level_4', models.CharField(blank=True, max_length=255, null=True)),
                ('one_mass', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('code_string', models.CharField(blank=True, max_length=1000, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('document_id', models.CharField(blank=True, max_length=36, null=True)),
                ('available', models.FloatField(blank=True, null=True)),
                ('free_available', models.FloatField(blank=True, null=True)),
                ('rest_available', models.FloatField(blank=True, null=True)),
                ('shipped_available', models.FloatField(blank=True, null=True)),
                ('moving', models.FloatField(blank=True, null=True)),
                ('delivered', models.FloatField(blank=True, null=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.contractor')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.object')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.materialtype')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.objecttype'),
        ),
        migrations.CreateModel(
            name='DeliveryQueryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codes_string', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('delivery_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_management.deliveryquery')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryquery',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.object'),
        ),
    ]
