# Generated by Django 4.0.5 on 2023-02-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='available',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='free_available',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='moving',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='rest_available',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='shipped_available',
        ),
        migrations.AlterField(
            model_name='deliveryquery',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_management.contractor'),
        ),
        migrations.AlterField(
            model_name='deliveryquery',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_management.object'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_management.contractor'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_management.object'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_management.materialtype'),
        ),
        migrations.CreateModel(
            name='RequirementDistributionAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('distribution_attribute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='material_management.distributionattributes')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='material_management.requirement')),
            ],
            options={
                'unique_together': {('distribution_attribute', 'requirement')},
            },
        ),
    ]
