# Generated by Django 4.0.5 on 2023-02-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_management', '0002_distributionattributes_remove_requirement_available_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryquery',
            table='delivery_query',
        ),
        migrations.AlterModelTable(
            name='deliveryqueryposition',
            table='delivery_query_position',
        ),
        migrations.AlterModelTable(
            name='distributionattributes',
            table='distribution_attribute',
        ),
        migrations.AlterModelTable(
            name='materialtype',
            table='material_type',
        ),
        migrations.AlterModelTable(
            name='objecttype',
            table='object_type',
        ),
        migrations.AlterModelTable(
            name='requirementdistributionattributevalue',
            table='requirement_distribution_attribute_value',
        ),
    ]
