# Generated by Django 4.0.5 on 2023-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management', '0004_rename_distributionattributes_distributionattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
