# Generated by Django 4.0.5 on 2023-02-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_management', '0005_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.object'),
        ),
    ]
