# Generated by Django 4.0.5 on 2023-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management', '0007_deliveryquery_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('name', 'type')},
        ),
    ]
